### PR TITLE
Unfollow only "botted" people

### PR DESCRIPTION
**Pull request by simonuvarov**
The main point is that now you can unfollow people you have followed earlier so that people you want to read stay in your followings. Also I extracted some standalone functions "as mute_by_id" and "follow_by_id". Fixed logical problems with gaining "not-to-follow" list.

### CODE REVIEW

**Comment by simonuvarov** [comment]
Yes, in one of the commits I forgot to delete my tokens, but I regenerated them so everything is fine.

**Comment by Nickfost** [comment]
why'd you close this?

**Comment by simonuvarov** [comment]
I don't think this pr is going to be approved and I have changed a lot of code already and I think it'd be better to have two different repos

**Comment by simonuvarov** [comment]
Anyway, if someone needs my code I can open pr again.

**Comment by simonuvarov** [comment]
Just check out my repo because I did some improvements like delays, private functions for saving each operation (I mean follow/unfollow ops.), reading tokens from file (in json, I think it's much better to use files instead of constants) and I renamed functions because the names were too long to me (that's why I thought my pull request was not going to pass). I mean using 'auto_' makes the names too complicated and there were other inaccuracies in naming variables.

**Pull request closed without merging**
